import json

with open('/Users/hjxarchive/Multi-Chromatic-Spatial-Pattern-Classification/Final/00b_Consolidate_Vectors.ipynb') as f:
    d = json.load(f)

new_cells = [
    {
        "cell_type": "markdown", "metadata": {},
        "source": [
            "---\n",
            "## 6. Sixpack Rips + Relative Rips 결합 벡터 생성\n",
            "\n",
            "`Phase8_Relative_Rips.ipynb` 참고.\n",
            "시뮬레이션 원본 데이터(Pos/Types)에서 Relative Barcode H*(K,L)을 직접 계산하고,\n",
            "기존 Sixpack_Rips 벡터와 결합하여 `Sixpack_Rips_Combined/`에 저장.\n",
            "\n",
            "**수행 과정:**\n",
            "1. L=Rips(A) ⊆ K=Rips(A∪B) inclusion의 Relative Barcode 계산\n",
            "2. Relative Barcode → PI 벡터화\n",
            "3. 기존 Sixpack_Rips npz + Relative PI → 결합 저장"
        ]
    },
    {
        "cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [],
        "source": [
            "import gc, psutil\n",
            "from gudhi import RipsComplex\n",
            "from persim import PersistenceImager\n",
            "import persim.images_weights as weights\n",
            "from collections import defaultdict"
        ]
    },
    {
        "cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [],
        "source": [
            "# --- Rips & Filtration Utilities ---\n",
            "\n",
            "def compute_Rips(points, max_edge=10):\n",
            "    rips = RipsComplex(points=points, max_edge_length=max_edge)\n",
            "    return rips.create_simplex_tree(max_dimension=2)\n",
            "\n",
            "def divide_filtration(st):\n",
            "    pairs = [(tuple(sorted(s)), f) for s, f in st.get_filtration()]\n",
            "    return [p[0] for p in pairs], [p[1] for p in pairs]\n",
            "\n",
            "# --- Relative Barcode ---\n",
            "\n",
            "def compute_relative_barcode_only(A, B, max_edge=10):\n",
            "    \"\"\"Inclusion L=Rips(A) ⊆ K=Rips(A∪B)의 Relative Persistence Barcode H*(K,L) 계산.\"\"\"\n",
            "    total = np.concatenate([A, B], axis=0)\n",
            "    a_len = len(A)\n",
            "    st = compute_Rips(total, max_edge=max_edge)\n",
            "    simplices, filt = divide_filtration(st)\n",
            "    del st, total; gc.collect()\n",
            "\n",
            "    idx_KmL = [i for i, s in enumerate(simplices) if any(v >= a_len for v in s)]\n",
            "    set_idx_KmL = set(idx_KmL)\n",
            "    KmL_pos = {g: l for l, g in enumerate(idx_KmL)}\n",
            "\n",
            "    sf_to_idx = {s: i for i, s in enumerate(simplices)}\n",
            "    Drel = []\n",
            "    for g_idx in idx_KmL:\n",
            "        s = simplices[g_idx]\n",
            "        rows = set()\n",
            "        if len(s) > 1:\n",
            "            for j in range(len(s)):\n",
            "                face = s[:j] + s[j+1:]\n",
            "                face_idx = sf_to_idx.get(face)\n",
            "                if face_idx in set_idx_KmL:\n",
            "                    rows.add(KmL_pos[face_idx])\n",
            "        Drel.append(rows)\n",
            "    del sf_to_idx, set_idx_KmL, KmL_pos; gc.collect()\n",
            "\n",
            "    def _reduce_fast(columns):\n",
            "        m = len(columns)\n",
            "        R = [set(col) for col in columns]\n",
            "        low = [-1] * m\n",
            "        pivot_of_row = {}\n",
            "        for i in range(m):\n",
            "            while R[i]:\n",
            "                li = max(R[i])\n",
            "                if li in pivot_of_row:\n",
            "                    R[i] ^= R[pivot_of_row[li]]\n",
            "                else:\n",
            "                    pivot_of_row[li] = i; low[i] = li; break\n",
            "        return R, low\n",
            "\n",
            "    Rrel, lowrel = _reduce_fast(Drel)\n",
            "    del Drel; gc.collect()\n",
            "\n",
            "    rel_bars = defaultdict(list)\n",
            "    for pos in range(len(idx_KmL)):\n",
            "        if lowrel[pos] != -1:\n",
            "            sigma = idx_KmL[lowrel[pos]]\n",
            "            tau = idx_KmL[pos]\n",
            "            b, d = filt[sigma], filt[tau]\n",
            "            if abs(b - d) > 1e-12:\n",
            "                p = len(simplices[sigma]) - 1\n",
            "                rel_bars[p].append((b, d))\n",
            "    del Rrel, lowrel, idx_KmL, simplices, filt; gc.collect()\n",
            "\n",
            "    out = {}\n",
            "    for p in [0, 1, 2]:\n",
            "        if p in rel_bars and rel_bars[p]:\n",
            "            arr = np.array(rel_bars[p])\n",
            "            out[p] = arr[np.lexsort((arr[:,1], arr[:,0]))]\n",
            "        else:\n",
            "            out[p] = np.empty((0, 2))\n",
            "    return {'relative': out}"
        ]
    },
    {
        "cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [],
        "source": [
            "# --- Persistence Image ---\n",
            "\n",
            "def compute_PIs(barcodes, max_eps=20, px_res=0.1, sigma=0.05, normalization=False):\n",
            "    for key in barcodes:\n",
            "        if len(barcodes[key]) == 0: barcodes[key] = np.zeros((0, 2))\n",
            "    vector = {}\n",
            "    # H0\n",
            "    pi0 = PersistenceImager(pixel_size=px_res, birth_range=(0,1), pers_range=(0,max_eps))\n",
            "    pi0.weight = weights.persistence; pi0.weight_params = {'n':1}\n",
            "    pi0.kernel_params = {'sigma': [[sigma,0],[0,sigma]]}\n",
            "    bars0 = np.array(barcodes.get(0, np.zeros((0,2))))\n",
            "    if len(bars0) > 0:\n",
            "        img0 = pi0.transform(bars0, skew=False)\n",
            "    else:\n",
            "        img0 = np.zeros((int(1/px_res), int(max_eps/px_res)))\n",
            "    vector[0] = np.mean(img0, axis=0)\n",
            "    # H1\n",
            "    pi1 = PersistenceImager(pixel_size=px_res, birth_range=(0,max_eps), pers_range=(0,max_eps/2))\n",
            "    pi1.weight = weights.persistence; pi1.weight_params = {'n':1}\n",
            "    pi1.kernel_params = {'sigma': [[sigma,0],[0,sigma]]}\n",
            "    bars1 = np.array(barcodes.get(1, np.zeros((0,2))))\n",
            "    if len(bars1) > 0:\n",
            "        img1 = pi1.transform(bars1, skew=True)\n",
            "    else:\n",
            "        img1 = np.zeros((int(max_eps/px_res), int((max_eps/2)/px_res)))\n",
            "    vector[1] = img1.flatten()\n",
            "    return vector"
        ]
    },
    {
        "cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [],
        "source": [
            "# --- 설정 ---\n",
            "\n",
            "MAX_EDGE = 10\n",
            "A_VALS = [0.0, 0.01, 0.05, 0.09, 0.13, 0.17, 0.21, 0.25]\n",
            "PARAM_LIST = [(x1, x2, x3) for x1 in A_VALS for x2 in A_VALS for x3 in A_VALS]\n",
            "\n",
            "RIPS_SRC = os.path.join(OUTPUT_BASE, 'Sixpack_Rips')        # 기존 Sixpack_Rips\n",
            "REL_OUT  = os.path.join(OUTPUT_BASE, 'Relative_Rips')       # Relative 단독 저장\n",
            "COMB_OUT = os.path.join(OUTPUT_BASE, 'Sixpack_Rips_Combined')  # 결합 저장\n",
            "os.makedirs(REL_OUT, exist_ok=True)\n",
            "os.makedirs(COMB_OUT, exist_ok=True)\n",
            "\n",
            "def get_ram_mb():\n",
            "    return psutil.Process(os.getpid()).memory_info().rss / 1024 / 1024\n",
            "\n",
            "print(f'Sixpack_Rips source: {RIPS_SRC}')\n",
            "print(f'Relative output:     {REL_OUT}')\n",
            "print(f'Combined output:     {COMB_OUT}')\n",
            "print(f'Total samples:       {len(PARAM_LIST)}')"
        ]
    },
    {
        "cell_type": "markdown", "metadata": {},
        "source": [
            "### 6-1. Relative Rips Barcode 계산 & PI 저장"
        ]
    },
    {
        "cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [],
        "source": [
            "START_IDX = 1\n",
            "END_IDX = 512\n",
            "\n",
            "for idx in range(START_IDX, END_IDX + 1):\n",
            "    rel_path = os.path.join(REL_OUT, f'Relative_Rips_{idx}.npz')\n",
            "    if os.path.exists(rel_path):\n",
            "        continue  # 이미 계산됨\n",
            "\n",
            "    params = PARAM_LIST[idx - 1]\n",
            "    folder = os.path.join(BASE_DIR, f'ParamSweep_{idx}_Output')\n",
            "    pos_file = os.path.join(folder, f'Pos_{params[0]:.2f}_{params[1]:.2f}_{params[2]:.2f}.dat')\n",
            "    types_file = os.path.join(folder, f'Types_{params[0]:.2f}_{params[1]:.2f}_{params[2]:.2f}.dat')\n",
            "\n",
            "    if not os.path.exists(pos_file):\n",
            "        print(f'[{idx}] SKIP - simulation data not found')\n",
            "        continue\n",
            "\n",
            "    print(f'[{idx}] Computing Relative Rips... (RAM: {get_ram_mb():.0f}MB)', end=' ')\n",
            "    t0 = time.time()\n",
            "\n",
            "    try:\n",
            "        types = np.loadtxt(types_file, dtype=int)\n",
            "        positions = np.loadtxt(pos_file, delimiter=',')\n",
            "        A = positions[types == 1]; B = positions[types == 2]\n",
            "        del types, positions\n",
            "\n",
            "        rel_A2B = compute_relative_barcode_only(A, B, max_edge=MAX_EDGE)\n",
            "        gc.collect()\n",
            "        rel_B2A = compute_relative_barcode_only(B, A, max_edge=MAX_EDGE)\n",
            "        gc.collect()\n",
            "        del A, B\n",
            "\n",
            "        PI_A2B = {k: compute_PIs(rel_A2B[k], max_eps=MAX_EDGE*2) for k in rel_A2B}\n",
            "        del rel_A2B\n",
            "        PI_B2A = {k: compute_PIs(rel_B2A[k], max_eps=MAX_EDGE*2) for k in rel_B2A}\n",
            "        del rel_B2A; gc.collect()\n",
            "\n",
            "        np.savez_compressed(rel_path, PI_A2B, PI_B2A)\n",
            "        del PI_A2B, PI_B2A; gc.collect()\n",
            "        print(f'OK ({time.time()-t0:.1f}s)')\n",
            "\n",
            "    except Exception as e:\n",
            "        print(f'ERROR: {e}')\n",
            "\n",
            "print('\\nRelative Rips 계산 완료')"
        ]
    },
    {
        "cell_type": "markdown", "metadata": {},
        "source": [
            "### 6-2. Sixpack_Rips + Relative_Rips 결합 저장"
        ]
    },
    {
        "cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [],
        "source": [
            "combined_count = 0\n",
            "\n",
            "for idx in range(1, 513):\n",
            "    comb_path = os.path.join(COMB_OUT, f'Sixpack_Rips_Combined_{idx}.npz')\n",
            "    if os.path.exists(comb_path):\n",
            "        combined_count += 1\n",
            "        continue\n",
            "\n",
            "    rips_file = os.path.join(RIPS_SRC, f'Sixpack_Rips_{idx}.npz')\n",
            "    rel_file = os.path.join(REL_OUT, f'Relative_Rips_{idx}.npz')\n",
            "\n",
            "    if not os.path.exists(rips_file):\n",
            "        continue\n",
            "    if not os.path.exists(rel_file):\n",
            "        continue\n",
            "\n",
            "    try:\n",
            "        rips_data = np.load(rips_file, allow_pickle=True)\n",
            "        rel_data = np.load(rel_file, allow_pickle=True)\n",
            "\n",
            "        # 결합: 기존 arr_0, arr_1 (Sixpack) + arr_0, arr_1 (Relative)\n",
            "        np.savez_compressed(\n",
            "            comb_path,\n",
            "            sixpack_A2B=rips_data['arr_0'],\n",
            "            sixpack_B2A=rips_data['arr_1'],\n",
            "            relative_A2B=rel_data['arr_0'],\n",
            "            relative_B2A=rel_data['arr_1'],\n",
            "        )\n",
            "        combined_count += 1\n",
            "        del rips_data, rel_data\n",
            "    except Exception as e:\n",
            "        print(f'[{idx}] ERROR: {e}')\n",
            "\n",
            "print(f'결합 완료: {combined_count}/512 files in {COMB_OUT}')"
        ]
    },
    {
        "cell_type": "markdown", "metadata": {},
        "source": [
            "### 6-3. 결합 결과 검증"
        ]
    },
    {
        "cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [],
        "source": [
            "# 검증\n",
            "rel_files = glob.glob(os.path.join(REL_OUT, 'Relative_Rips_*.npz'))\n",
            "comb_files = glob.glob(os.path.join(COMB_OUT, 'Sixpack_Rips_Combined_*.npz'))\n",
            "\n",
            "print('=== 결과 요약 ===')\n",
            "print(f'Relative_Rips:          {len(rel_files)}/512')\n",
            "print(f'Sixpack_Rips_Combined:  {len(comb_files)}/512')\n",
            "\n",
            "# 샘플 로드 테스트\n",
            "if comb_files:\n",
            "    test = np.load(sorted(comb_files)[0], allow_pickle=True)\n",
            "    print(f'\\n샘플 파일 키: {list(test.keys())}')\n",
            "    for k in test.keys():\n",
            "        v = test[k]\n",
            "        if hasattr(v, 'shape'):\n",
            "            print(f'  {k}: shape={v.shape}, dtype={v.dtype}')\n",
            "        else:\n",
            "            print(f'  {k}: type={type(v)}')"
        ]
    }
]

d["cells"].extend(new_cells)

with open('/Users/hjxarchive/Multi-Chromatic-Spatial-Pattern-Classification/Final/00b_Consolidate_Vectors.ipynb', 'w') as f:
    json.dump(d, f, ensure_ascii=False, indent=1)

print(f'Updated: {len(d["cells"])} cells')
